#!/usr/bin/env ruby
# vim: set ft=ruby:

require 'fileutils'

class Store
  attr_reader :file_path

  def initialize
    @file_path = File.join(Dir.home, '.fantassh')
    FileUtils.touch(@file_path)
  end

  def entries
    File.readlines(@file_path)
  end

  def add(new_entries)
    entries = (self.entries + new_entries).map(&:strip).uniq

    File.open(@file_path, 'w') do |f|
      f.puts(entries)
    end
  end
end

class BashHistory
  def entries
    File.readlines(File.join(Dir.home, '.bash_history')).
      grep(/^ssh/).
      uniq.
      map { |x| x.gsub(/^ssh/, '') }
  end
end

class FantaSsh
  def initialize
    @store = Store.new
    @bash_history = BashHistory.new
  end

  def run
    @store.add(@bash_history.entries)
    exec "ssh $(cat #{@store.file_path} | selecta)"
  end
end

FantaSsh.new.run
